[project]
name = "chemmanager"
version = "0.1.0"
description = "Open chemistry inventory manager."
authors = [
    {name = "Whitie",email = "weimann.th@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.10,<4"
dependencies = [
    "django (>=5.2.4,<6.0.0)",
    "django-q2 (>=1.8.0,<2.0.0)",
    "django-auth-ldap (>=5.2.0,<6.0.0)",
    "cryptography (>=45.0.5,<46.0.0)",
    "django-contrib-comments (>=2.2.0,<3.0.0)",
    "django-jinja (>=2.11.0,<3.0.0)",
    "django-spaghetti-and-meatballs (>=0.4.2,<0.5.0)",
    "pillow (>=11.3.0,<12.0.0)",
    "pubchempy (>=1.0.4,<2.0.0)",
    "pygments (>=2.19.2,<3.0.0)",
    "qrcode (>=8.2,<9.0)",
    "openpyxl (>=3.1.5,<4.0.0)",
    "weasyprint (>=65.1,<66.0)",
    "djangorestframework (>=3.16.0,<4.0.0)",
    "gunicorn (>=23.0.0,<24.0.0)",
    "psycopg2-binary (>=2.9.10,<3.0.0)",
    "requests (>=2.32.4,<3.0.0)",
    "babel (>=2.17.0,<3.0.0)"
]

[tool.poetry]

[tool.poetry.group.dev.dependencies]
flake8 = "^7.3.0"
black = "^25.1.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
