# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import floor_map.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20161231_0735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0, verbose_name='Level')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('map', models.ImageField(upload_to=floor_map.models.get_floor_image_path, verbose_name='Map')),
                ('map_h', models.PositiveIntegerField(default=0)),
                ('map_w', models.PositiveIntegerField(default=0)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='core.Building', verbose_name='Building')),
            ],
            options={
                'verbose_name_plural': 'Floors',
                'verbose_name': 'Floor',
                'ordering': ['building', 'level'],
            },
        ),
        migrations.CreateModel(
            name='FloorStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0, verbose_name='X')),
                ('y', models.IntegerField(default=0, verbose_name='Y')),
                ('storage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='floor', to='core.Storage', verbose_name='Storage')),
            ],
            options={
                'verbose_name_plural': 'Floor Storages',
                'verbose_name': 'Floor Storage',
                'ordering': ['storage'],
            },
        ),
    ]
