# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161231_0735'),
        ('floor_map', '0002_auto_20170103_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floor',
            options={'ordering': ['building', 'level'], 'verbose_name': 'Floor', 'verbose_name_plural': 'Floors'},
        ),
        migrations.AlterUniqueTogether(
            name='floor',
            unique_together=set([('building', 'level')]),
        ),
    ]
