# Generated by Django 4.1.4 on 2022-12-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("floor_map", "0003_auto_20170103_1452"),
    ]

    operations = [
        migrations.AlterField(
            model_name="floor",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="floorstorage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
