# Generated by Django 2.2.9 on 2020-02-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating_instruction_creator', '0003_auto_20200205_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstAidPictogram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(max_length=10, verbose_name='Identifier')),
                ('icon', models.FileField(upload_to='oic')),
                ('description', models.CharField(blank=True, max_length=30, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'First Aid Pictogram',
                'verbose_name_plural': 'First Aid Pictograms',
                'ordering': ['ident'],
            },
        ),
        migrations.AddField(
            model_name='protectionpictogram',
            name='description',
            field=models.CharField(blank=True, max_length=30, verbose_name='Description'),
        ),
    ]
