# Generated by Django 2.2.15 on 2021-09-30 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210930_1840'),
        ('operating_instruction_creator', '0004_auto_20200206_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatinginstructiondraft',
            name='saved_as',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.OperatingInstruction', verbose_name='Saved as'),
        ),
    ]
