# Generated by Django 2.2.15 on 2022-03-31 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating_instruction_creator', '0005_operatinginstructiondraft_saved_as'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatinginstructiondraft',
            name='msds_date',
            field=models.DateField(blank=True, null=True, verbose_name='MSDS Date'),
        ),
    ]
