# Generated by Django 2.2.15 on 2022-05-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating_instruction_creator', '0006_operatinginstructiondraft_msds_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatinginstructiondraft',
            name='conduct_pics',
            field=models.ManyToManyField(blank=True, related_name='drafts', to='operating_instruction_creator.ProtectionPictogram', verbose_name='Conduct Pictograms'),
        ),
    ]
