# Generated by Django 4.1.4 on 2022-12-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "operating_instruction_creator",
            "0007_operatinginstructiondraft_conduct_pics",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="firstaidpictogram",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="operatinginstructiondraft",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="protectionpictogram",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="workdepartment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
