# Generated by Django 5.2.8 on 2025-11-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operating_instruction_creator", "0008_alter_firstaidpictogram_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operatinginstructiondraft",
            name="extra_info",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Extra Info"
            ),
        ),
    ]
