# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-24 09:40
from __future__ import unicode_literals

import core.fields
import core.models.chems
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedMSDS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='uploaded_msds/%Y/', verbose_name='Document')),
                ('hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Added')),
                ('processed', models.BooleanField(default=False, verbose_name='Processed')),
                ('data', core.fields.JSONField(blank=True, editable=False, verbose_name='Extracted Data')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Name')),
                ('cas', models.CharField(blank=True, max_length=12, validators=[core.models.chems.validate_cas], verbose_name='CAS Registry Number')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL, verbose_name='Added by')),
            ],
            options={
                'verbose_name_plural': "Uploaded MSDS's",
                'permissions': (('upload', 'Can upload msds'),),
                'ordering': ['-added'],
                'verbose_name': 'Uploaded MSDS',
            },
        ),
    ]
