# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-26 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msds_collector', '0002_parseddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedmsds',
            name='token',
            field=models.CharField(default='12345', editable=False, max_length=64, verbose_name='Security token'),
            preserve_default=False,
        ),
    ]
