# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-26 07:40
from __future__ import unicode_literals

import core.models.chems
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msds_collector', '0003_uploadedmsds_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseddata',
            name='article_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Article name'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='article_number',
            field=models.CharField(blank=True, max_length=64, verbose_name='Article number'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='boiling_high',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='In °C.', max_digits=5, null=True, verbose_name='Boiling Point high'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='boiling_low',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='In °C.', max_digits=5, null=True, verbose_name='Boiling Point low'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='bulk_density',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='In kg/m3.', max_digits=10, null=True, verbose_name='Bulk Density'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='cmr',
            field=models.BooleanField(default=False, verbose_name='CMR Substance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parseddata',
            name='color',
            field=models.CharField(blank=True, max_length=30, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='density',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='In g/cm3.', max_digits=10, null=True, verbose_name='Density'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='density_temp',
            field=models.IntegerField(blank=True, help_text='In °C.', null=True, verbose_name='Density at Temperature'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='einecs',
            field=models.CharField(blank=True, max_length=9, validators=[core.models.chems.validate_ecn], verbose_name='EC Number'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='euh',
            field=models.CharField(blank=True, max_length=100, verbose_name='EUH'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='ext_agents',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='fire_misc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='formula',
            field=models.CharField(blank=True, max_length=200, verbose_name='Molecular Formula'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='h',
            field=models.CharField(blank=True, max_length=200, verbose_name='H'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='hin',
            field=models.CharField(blank=True, help_text='Hazard Identification Number', max_length=5, verbose_name='HIN'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='inchi',
            field=models.TextField(blank=True, verbose_name='InChI'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='inchi_key',
            field=models.CharField(blank=True, max_length=30, verbose_name='InChI-Key'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='ioelv',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Indicative Occupational Exposure Limit (mg/m3)', max_digits=10, null=True, verbose_name='IOELV'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='iupac_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='IUPAC Name'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='iupac_name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='IUPAC Name (en)'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='mabc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='MABC'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='mabc_unit',
            field=models.CharField(default='mg/L', max_length=5, verbose_name='MABC Unit'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='mac',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='MAC'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='mac_unit',
            field=models.CharField(default='mg/m3', max_length=5, verbose_name='MAC unit'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='melting_high',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='In °C.', max_digits=5, null=True, verbose_name='Melting Point high'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='melting_low',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='In °C.', max_digits=5, null=True, verbose_name='Melting Point low'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='molar_mass',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Molar Mass'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Name (en)'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='no_ext_agents',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='odor',
            field=models.CharField(blank=True, max_length=30, verbose_name='Odor'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='p',
            field=models.CharField(blank=True, max_length=200, verbose_name='P'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='physical_state',
            field=models.CharField(blank=True, choices=[('s', 'solid'), ('l', 'liquid'), ('g', 'gaseous')], max_length=1, verbose_name='Physical State'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='producer',
            field=models.CharField(blank=True, max_length=200, verbose_name='Producer'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='pubchem_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='PubChem Compound ID'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='review_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last review'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='security',
            field=models.CharField(blank=True, max_length=100, verbose_name='Extra security'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='signal_word',
            field=models.CharField(blank=True, choices=[('', '-'), ('danger', 'Danger'), ('warning', 'Warning')], max_length=25, verbose_name='Signal Word'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='smiles',
            field=models.TextField(blank=True, verbose_name='SMILES'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='solubility_h2o',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='In g/100g.', max_digits=10, null=True, verbose_name='Solubility (H2O)'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='solubility_h2o_temp',
            field=models.IntegerField(blank=True, help_text='In °C.', null=True, verbose_name='Solubility at Temperature'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='storage_class',
            field=models.CharField(blank=True, max_length=10, verbose_name='Storage class'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='structure',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='symbols',
            field=models.CharField(blank=True, max_length=200, verbose_name='Symbols'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='synonyms',
            field=models.TextField(blank=True, help_text='Separate with ";".', verbose_name='Synonyms'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='vwvws',
            field=models.IntegerField(blank=True, null=True, verbose_name='DE: VWVWS'),
        ),
        migrations.AddField(
            model_name='parseddata',
            name='whc',
            field=models.PositiveSmallIntegerField(choices=[(0, '0 - Non-hazardous to water'), (1, '1 - Low hazard to waters'), (2, '2 - Hazard to waters'), (3, '3 - Severe hazard to waters')], default=0, help_text='Water Hazard Class', verbose_name='WHC'),
        ),
    ]
