# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-26 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msds_collector', '0004_auto_20170726_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parseddata',
            name='mabc_unit',
        ),
        migrations.RemoveField(
            model_name='parseddata',
            name='mac_unit',
        ),
        migrations.AlterField(
            model_name='parseddata',
            name='mabc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='MABC (mg/L)'),
        ),
        migrations.AlterField(
            model_name='parseddata',
            name='mac',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='MAC (mg/m3)'),
        ),
    ]
