# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-26 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msds_collector', '0005_auto_20170726_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parseddata',
            name='structure',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
