# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-27 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msds_collector', '0007_auto_20170727_0704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parseddata',
            options={'ordering': ['name_en'], 'verbose_name': 'Parsed upload data', 'verbose_name_plural': 'Parsed upload data'},
        ),
    ]
