# Generated by Django 4.1.4 on 2022-12-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msds_collector", "0011_auto_20200217_1238"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parseddata",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="uploadedmsds",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
