# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161231_0735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storage',
            options={'ordering': ['department', 'name'], 'permissions': (('can_store', 'Can store chemicals'), ('can_consume', 'Can consume chemicals'), ('can_transfer', 'Can transfer chemicals'), ('can_dispose', 'Can dispose chemicals'), ('set_limits', 'Can set stocklimits'), ('inventory', 'Can make inventory')), 'verbose_name': 'Storage', 'verbose_name_plural': 'Storages'},
        ),
    ]
