# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 08:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20170206_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('info', 'Information'), ('danger', 'Important Information'), ('success', 'Message')], default='warning', max_length=7, verbose_name='Type')),
                ('message', models.TextField(help_text='You can use HTML in this field.', verbose_name='Message')),
                ('timeout', models.PositiveIntegerField(default=5, help_text='After this number of seconds the message will disappear from screen. Use 0 to force the user to click it away.', verbose_name='Timeout')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='Added')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('seen_by', models.ManyToManyField(blank=True, related_name='seen_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Seen by')),
            ],
            options={
                'ordering': ['-added'],
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
    ]
