# Generated by Django 2.2.9 on 2020-01-24 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170724_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='unit',
            field=models.CharField(blank=True, choices=[('g', 'g'), ('µg', 'µg'), ('mg', 'mg'), ('kg', 'kg'), ('mL', 'mL'), ('L', 'L')], max_length=2, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='chaptercomment',
            name='author',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paragraph_comments', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='added_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Added by'),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='storage_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chemicals', to='core.StorageClass', verbose_name='Storage Class'),
        ),
        migrations.AlterField(
            model_name='consume',
            name='department',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumes', to='core.Department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='consume',
            name='unit',
            field=models.CharField(choices=[('g', 'g'), ('µg', 'µg'), ('mg', 'mg'), ('kg', 'kg'), ('mL', 'mL'), ('L', 'L')], max_length=2, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='inventorydifference',
            name='unit',
            field=models.CharField(choices=[('g', 'g'), ('µg', 'µg'), ('mg', 'mg'), ('kg', 'kg'), ('mL', 'mL'), ('L', 'L')], max_length=2, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='inventorydifference',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='legallimit',
            name='unit',
            field=models.CharField(choices=[('g', 'g'), ('µg', 'µg'), ('mg', 'mg'), ('kg', 'kg'), ('mL', 'mL'), ('L', 'L')], default='kg', max_length=2, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='operatinginstruction',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Last updated by'),
        ),
        migrations.AlterField(
            model_name='packageusage',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_packages', to='core.Group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='packageusage',
            name='mass_after_unit',
            field=models.CharField(choices=[('g', 'g'), ('µg', 'µg'), ('mg', 'mg'), ('kg', 'kg')], default='g', max_length=2, verbose_name='Mass after Unit'),
        ),
        migrations.AlterField(
            model_name='packageusage',
            name='removed_quantity_unit',
            field=models.CharField(choices=[('g', 'g'), ('µg', 'µg'), ('mg', 'mg'), ('kg', 'kg'), ('mL', 'mL'), ('L', 'L')], default='g', max_length=2, verbose_name='Removed Quantity Unit'),
        ),
        migrations.AlterField(
            model_name='packageusage',
            name='used_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='packageusage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_usages', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='author',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_paragraphs', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_paragraphs', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        migrations.AlterField(
            model_name='stocklimit',
            name='unit',
            field=models.CharField(choices=[('g', 'g'), ('µg', 'µg'), ('mg', 'mg'), ('kg', 'kg'), ('mL', 'mL'), ('L', 'L')], default='g', max_length=2, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='storedchemical',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stored_chemicals', to='core.Company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='storedchemical',
            name='msds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stored_chemicals', to='core.MaterialSafetyDataSheet', verbose_name='Material Safety Data Sheet'),
        ),
        migrations.AlterField(
            model_name='storedpackage',
            name='brutto_mass_unit',
            field=models.CharField(choices=[('g', 'g'), ('µg', 'µg'), ('mg', 'mg'), ('kg', 'kg')], default='g', max_length=2, verbose_name='Brutto Mass Unit'),
        ),
        migrations.AlterField(
            model_name='storedpackage',
            name='disposed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Stored by'),
        ),
        migrations.AlterField(
            model_name='storedpackage',
            name='stored_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stored_packages', to=settings.AUTH_USER_MODEL, verbose_name='Stored by'),
        ),
        migrations.AlterField(
            model_name='storedpackage',
            name='unit',
            field=models.CharField(choices=[('g', 'g'), ('µg', 'µg'), ('mg', 'mg'), ('kg', 'kg'), ('mL', 'mL'), ('L', 'L')], max_length=2, verbose_name='Unit'),
        ),
    ]
