# Generated by Django 2.2.15 on 2021-09-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200124_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedchemical',
            name='quality',
            field=models.CharField(blank=True, choices=[('selfmade', 'Self made'), ('technical', 'technically'), ('synthesis', 'for synthesis'), ('purest', 'purest'), ('pheur', 'Ph. Eur.'), ('analysis', 'for analysis'), ('special', 'special')], default='', help_text='Choose special here if no quality match. Give exact quality in the extra field.', max_length=15, verbose_name='Quality'),
        ),
        migrations.AlterField(
            model_name='storedpackage',
            name='container_material',
            field=models.CharField(choices=[('plastic', 'Plastic'), ('glass', 'Glass'), ('alu', 'Aluminium'), ('carton', 'Carton'), ('bag', 'Bag'), ('canister', 'Canister'), ('hobbock', 'Hobbock'), ('barrel', 'Barrel'), ('pallet', 'Pallet')], default='plastic', max_length=10, verbose_name='Container Material'),
        ),
    ]
