# Generated by Django 2.2.15 on 2021-10-13 10:02

from django.db import migrations, models
from decimal import Decimal


def update_solubility(apps, schema_editor):
    PhysicalData = apps.get_model('core', 'PhysicalData')
    factor = Decimal(10)
    for pd in PhysicalData.objects.filter(solubility_h2o__isnull=False):
        pd.solubility_h2o = pd.solubility_h2o * factor
        pd.save(update_fields=['solubility_h2o'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210930_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicaldata',
            name='solubility_h2o',
            field=models.DecimalField(
                blank=True, decimal_places=4, help_text='In g/L.',
                max_digits=10, null=True, verbose_name='Solubility (H2O)'
            ),
        ),
        migrations.RunPython(
            update_solubility, reverse_code=migrations.RunPython.noop
        ),
    ]
